import type { Meta, StoryObj } from "@storybook/react";
import { Input } from "./input.js";
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Default: Story;
export declare const Error: Story;
export declare const Success: Story;
export declare const Small: Story;
export declare const Large: Story;
