import type { Meta, StoryObj } from "@storybook/react";
import { Badge } from "./badge.js";
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof Badge>;
export declare const Default: Story;
export declare const Success: Story;
export declare const Error: Story;
export declare const Info: Story;
export declare const Warning: Story;
export declare const Muted: Story;
export declare const Square: Story;
