import type { Meta, StoryObj } from "@storybook/react";
import { Textarea } from "./textarea.js";
declare const meta: Meta<typeof Textarea>;
export default meta;
type Story = StoryObj<typeof Textarea>;
export declare const Default: Story;
export declare const Error: Story;
export declare const Success: Story;
export declare const Small: Story;
export declare const Large: Story;
