import type { Meta, StoryObj } from "@storybook/react";
import { Switch } from "./switch.js";
declare const meta: Meta<typeof Switch>;
export default meta;
type Story = StoryObj<typeof Switch>;
export declare const Default: Story;
export declare const Checked: Story;
export declare const Error: Story;
export declare const Success: Story;
export declare const Disabled: Story;
