import type { Meta, StoryObj } from "@storybook/react";
import { Select } from "./select.js";
declare const meta: Meta<typeof Select>;
export default meta;
type Story = StoryObj<typeof Select>;
export declare const Default: Story;
export declare const Error: Story;
export declare const Success: Story;
export declare const Small: Story;
export declare const Large: Story;
