import type { Meta, StoryObj } from "@storybook/react";
import { Tooltip } from "./tooltip.js";
declare const meta: Meta<typeof Tooltip>;
export default meta;
type Story = StoryObj<typeof Tooltip>;
export declare const Default: Story;
export declare const Top: Story;
export declare const Bottom: Story;
export declare const Left: Story;
export declare const Right: Story;
export declare const Large: Story;
